# Generated by Django 3.2.9 on 2021-11-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
