"""AQUI TRATAREMOS DE DOC STRING

SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON
SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON
SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON
SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON

SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON
SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON
SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON
SDSMSD SODISDON SDSMSD SODISDON SDSMSD SODISDON """


def soma (x,r):
    """função de soma()
    :param x: numero
    :type x: int or float

    :param r: numero
    :type r: int or float
    :return : retorna a soma
    :rtype: int or float"""
    return x + r


def mul(x,y):
    pass